int cad_tamanho(char s[]);
int cad_procurar_car(char c, char s[]);
int cad_ocorrencias(char c, char s[]);
int cad_procurar_str(char s1[], char s2[]);
int cad_e_prefixo(char s1[], char s2[]);
int cad_e_sufixo(char s1[], char s2[]);
int cad_iguais(char s1[], char s2[]);
int cad_primeiro(char s1[], char s2[]);
int cad_comparar(char s1[], char s2[]);
int cad_um_dos(char s1[], char s2[]);
int cad_nenhum_dos(char s1[], char s2[]);
int cad_copiar(char s1[], char s2[]);
int cad_colar(char s1[], char s2[]);
int cad_mover(char m1[], char m2[], int n);
